### ISSUE TITLE
Отсутствие Мили Атаки у Беса(Варлока)

### ISSUE THREAD

**Issue by kuzinsun** [moonwelltbc/bugtracker#11]
### После какого обновления появился баг?

last

### Описание багрепорта

При призыве Беса(Impa) Варлока.
Заклинание ->https://www.wowhead.com/spell=688/summon-imp
image
Если варлок вступает в бой и нажимает атаковать петом о не атакует мили ударами а просто стоит

### Как воспроизвести баг?

.

### Как должно работать?

Должен атаковать мили атакой?

**Comment by Gensen1** [comment]
https://www.wowhead.com/spell=688/summon-imp#comments
Please note that this demon has no melee attacks, he can only cast his firebolt.
