### ISSUE TITLE
Фир визуал

### ISSUE THREAD

**Issue by Gensen1** [moonwelltbc/bugtracker#13]
### После какого обновления появился баг?

1

### Описание багрепорта

![image](https://github.com/moonwelltbc/bugtracker/assets/64833670/6a633fc8-77b8-483a-b2eb-887ef2854453)

Цель на которой висит курса безрассудства нельзя фирнуть будет имун, не на бета тесте норм пишет имун
А на бете визуально фир а по факту нет
Визуальный баг - фира нет, но он показан

> фикс в старом репо

### Как воспроизвести баг?

1.
2.
3.
4.
5.
...

### Как должно работать?

1

**Comment by Ta-tsu-ka** [comment]
Фир, и должен висеть, так как перекидыванием проклятий ты управляешь фиром, не перевешивая его каждый раз.

**Comment by Gensen1** [comment]
> Фир, и должен висеть, так как перекидыванием проклятий ты управляешь фиром, не перевешивая его каждый раз. https://www.wowhead.com/tbc/spell=27226/curse-of-recklessness#comments:id=239666

Согласен.
