### ISSUE TITLE
Баф сукубыㅤ

### ISSUE THREAD

**Issue by Gensen1** [moonwelltbc/bugtracker#14]
### После какого обновления появился баг?

1

### Описание багрепорта

![image](https://github.com/moonwelltbc/bugtracker/assets/64833670/f330e4e3-c3d7-49b5-8ce4-0710d86fa6b3)

### Как воспроизвести баг?

1.
2.
3.
4.
5.
...

### Как должно работать?

1

**Comment by Hentaika** [comment]
Хочу добавить, что это не является багом, просто из-за некоторых обстоятельств этот баф был убран.
