### ISSUE TITLE
Кривые текстурки

### ISSUE THREAD

**Issue by Hentaika** [moonwelltbc/bugtracker#17]
### Описание багрепорта

![WoWScrnShot_071823_231029](https://github.com/moonwelltbc/bugtracker/assets/18301825/4fcef6f4-e414-4c5b-889d-0b65011e9521)
![WoWScrnShot_071823_231035](https://github.com/moonwelltbc/bugtracker/assets/18301825/180d5fb1-49f3-490f-90b7-1a3b1cc64f26)

### Как воспроизвести баг?

-

### Как должно работать?

-

### Игровой мир

Moonwell x100

### Версия ядра

72d8c67 (2023-07-18 02:14:32)

**Comment by Gensen1** [comment]
Была неправильная точка спавна (под землей)
