### ISSUE TITLE
[Blood Furnace] Техник клана Призрачной Луны / Shadowmoon Technician npc=17414

### ISSUE THREAD

**Issue by Hentaika** [moonwelltbc/bugtracker#33]
### Описание багрепорта

Ставит бомбы в воздухе.
![WoWScrnShot_072123_114639](https://github.com/moonwelltbc/bugtracker/assets/18301825/21ee4a1e-2410-48e1-9006-f127b273c76d)
![WoWScrnShot_072123_114854](https://github.com/moonwelltbc/bugtracker/assets/18301825/8c5a6dc6-c807-4cae-8576-2ab782e21928)
![WoWScrnShot_072123_115703](https://github.com/moonwelltbc/bugtracker/assets/18301825/7135e497-b39f-4d4c-bea5-b22305c7c1f4)

### Как воспроизвести баг?

-

### Как должно работать?

Должны быть внизу, а не висеть в воздухе.

### Игровой мир

Moonwell x100

### Версия ядра

72d8c67 (2023-07-18 02:14:32)

**Comment by Gensen1** [comment]
https://github.com/moonwelltbc/bugtracker/issues/32
