### ISSUE TITLE
Паладин может использовать БоП на дружественных целях, находясь в состоянии ослепления

### ISSUE THREAD

**Issue by kuzinsun** [moonwelltbc/bugtracker#4]
### После какого обновления появился баг?

last

### Описание багрепорта

Паладин находясь под блайндом https://db.moonwell.su/?spell=2094, может использовать https://db.moonwell.su/?spell=10278 на дружественную цель.

1. Можно использовать на себя во время стана, ошеломления, фира (только если сс физической школы). Фир вара, сап рога.
2. Нельзя использовать на тиммейтов находясь в сс. Только на себя, и только если п.1
3. Можно использовать на тиммейта, если сам паладин не в сс. При этом тиммейт может находится в сс и боп снимает cс (если он физической школы).

### Как воспроизвести баг?

1. Применяем ауру 2094 к персонажу №1
2. Персонажем №1 используем https://db.moonwell.su/?spell=10278 на дружественную цель
ОР: https://db.moonwell.su/?spell=10278 не кастуется на дружественную цель

### Как должно работать?

 Необходимо убрать возможность использовать https://db.moonwell.su/?spell=10278 на дружественную цель находясь под контролем.

### Дополнительная информация, скриншоты и видео

![image](https://github.com/wowmw/bugtracker-new/assets/60097141/234c7d7e-501f-4ffe-a238-8951bc77006c)

**Comment by Gensen1** [comment]
https://github.com/wowmw/mwcore-old/commit/b740c467c12b11df89b43e9f2c4a4ad28332a46d
