### ISSUE TITLE
Missed modifiers

### ISSUE THREAD

**Issue by Hentaika** [moonwelltbc/bugtracker#40]
### Описание багрепорта

1. Если кто то попал в туман, то его нельзя бить, а должно быть можно.
![image](https://github.com/moonwelltbc/bugtracker/assets/18301825/ad5f5d53-46a7-4ca8-8a11-825ed6f64116)

2. Недоработка с занижением урона для сервера х100. Заклинание https://www.wowhead.com/tbc/spell=45662 наносит 100% урон.
![image](https://github.com/moonwelltbc/bugtracker/assets/18301825/f8e7e1f7-f833-43f8-8a98-db7a3d976c61)

3. Также после убийства не исчезает огненная стена и нельзя идти к следующему боссу. Описано тут: https://github.com/moonwelltbc/bugtracker/issues/38

### Как воспроизвести баг?

-

### Как должно работать?

-

### Игровой мир

Moonwell x100

### Версия ядра

215cd4d (2023-07-21 13:28:25)

**Comment by Gensen1** [comment]
2) Триггер-аура инкапсулейта вешается на игрока, из-за чего игрок наносит урон окружающим игрокам, а не НПС. По этой причине не срабатывают модификаторы. Выставил модификатор вручную для инкапсулейта (на х100). В игре должны быть еще похожие спеллы, где нужно будет проставлять модификатор подобным образом.

**Comment by Hentaika** [comment]
> 2. Триггер-аура инкапсулейта вешается на игрока, из-за чего игрок наносит урон окружающим игрокам, а не НПС. По этой причине не срабатывают модификаторы. Выставил модификатор вручную для инкапсулейта (на х100). В игре должны быть еще похожие спеллы, где нужно будет проставлять модификатор подобным образом.

Такой же момент заметила с https://www.wowhead.com/tbc/spell=40810 у Матушки Шахраз в Чёрном Храме https://db.moonwell.su/?npc=22947.

**Comment by Hentaika** [comment]
> 2. Триггер-аура инкапсулейта вешается на игрока, из-за чего игрок наносит урон окружающим игрокам, а не НПС. По этой причине не срабатывают модификаторы. Выставил модификатор вручную для инкапсулейта (на х100). В игре должны быть еще похожие спеллы, где нужно будет проставлять модификатор подобным образом.

https://www.wowhead.com/tbc/ru/npc=25371 отсутствует занижение хила для абилок https://www.wowhead.com/tbc/ru/spell=46564 и https://www.wowhead.com/tbc/ru/spell=46563

**Comment by Hentaika** [comment]
> 2. Триггер-аура инкапсулейта вешается на игрока, из-за чего игрок наносит урон окружающим игрокам, а не НПС. По этой причине не срабатывают модификаторы. Выставил модификатор вручную для инкапсулейта (на х100). В игре должны быть еще похожие спеллы, где нужно будет проставлять модификатор подобным образом.

Техник клана Призрачной Луны / Shadowmoon Technician npc=17414
Не уменьшен урон от взрыва бомбы, которые ставит нпс:
![image](https://github.com/moonwelltbc/bugtracker/assets/18301825/a21ec46d-c7ce-4937-a5ac-2b24fd5ac53e)

**Comment by Gensen1** [comment]
Исправил все выше. Если будут найдены еще несоответствия в плане модификаторов урона - создайте новый багрепорт.
