### ISSUE TITLE
[Hunter] Питомец 

### ISSUE THREAD

**Issue by Ta-tsu-ka** [moonwelltbc/bugtracker#42]
### Описание багрепорта

он поломан: от панели питомца, до его характеристик.

### Как воспроизвести баг?

1.
2.
3.
4.
5.
...

### Как должно работать?

работать

### Игровой мир

Moonwell x100

### Версия ядра

d2a0ad9 (2023-07-23 18:39:06)

**Comment by Hentaika** [comment]
> ### Описание багрепорта
> он поломан: от панели питомца, до его характеристик.
> 
> ### Как воспроизвести баг?
> 
> ...
> 
> ### Как должно работать?
> работать
> 
> ### Игровой мир
> Moonwell x100
> 
> ### Версия ядра
> d2a0ad9 (2023-07-23 18:39:06)
> 
> ### Ваш игровой ник
> _No response_

Панель поломана как и у локов из-за переноса персонажей, я приручила хантом нового пета и с панелью стало всё ок.

**Comment by Hentaika** [comment]
Что касается занижений характеристик пета, то это из-за действующий занижений на х100.

Вот скрин с х100, на 70 лвл 3800 хп:
![image](https://github.com/moonwelltbc/bugtracker/assets/18301825/9ac3e011-7fa8-40e1-8a98-04da7bb63c5e)

А вот скрин с х5, на 65 лвл 4400 хп:
![image](https://github.com/moonwelltbc/bugtracker/assets/18301825/8ce8e41a-74ad-4c38-bd19-3272134b3dfb)

**Comment by Ta-tsu-ka** [comment]
а панель питомцев?

**Comment by Gensen1** [comment]
> а панель питомцев?

После релиза все петы будут удалены. Игрокам нужно будет приручать их заново. Следовательно, проблем с панелями уже не будет.
